[build]
  base = "apps/web/"
  command = "npx pnpm install --store=node_modules/.pnpm-store && pnpm -w run build"
  publish = "build/"

[build.environment]
  NPM_FLAGS = "--version"

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"
